"""
Marketing Mix Model

Fits OLS regression with log-transformed variables.
Computes channel elasticities, contribution decomposition, and ROI.
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from dataclasses import dataclass, field


@dataclass
class MMMResults:
    model: object
    feature_names: list
    elasticities: dict
    contributions: pd.DataFrame
    metrics: dict
    channel_costs: dict = field(default_factory=dict)
    roi: dict = field(default_factory=dict)


class MarketingMixModel:
    """
    OLS-based Marketing Mix Model with:
    - Log-log specification for elasticity interpretation
    - Channel contribution decomposition
    - ROI calculation per channel
    - Scenario simulation
    """

    def __init__(self):
        self.model = None
        self.feature_names = []
        self.results: MMMResults = None

    def fit(self, X: pd.DataFrame, y: pd.Series) -> "MarketingMixModel":
        self.feature_names = list(X.columns)
        X_const = sm.add_constant(X)
        self.model = sm.OLS(y, X_const).fit()
        return self

    def predict(self, X: pd.DataFrame) -> np.ndarray:
        X_const = sm.add_constant(X, has_constant="add")
        return self.model.predict(X_const)

    def get_elasticities(self) -> dict:
        """
        In a log-log model, coefficients ARE elasticities:
        1% increase in channel X -> beta% change in Rx claims.
        """
        params = self.model.params
        elasticities = {}
        for feat in self.feature_names:
            if feat in params.index:
                elasticities[feat] = round(float(params[feat]), 4)
        return elasticities

    def get_contributions(self, X: pd.DataFrame, y_actual: pd.Series) -> pd.DataFrame:
        """Decompose Rx claims by channel contribution."""
        params = self.model.params
        contributions = pd.DataFrame(index=X.index)
        contributions["base"] = float(params.get("const", 0))

        for feat in self.feature_names:
            if feat in params.index and feat in X.columns:
                contributions[feat] = params[feat] * X[feat]

        contributions["total_predicted"] = contributions.sum(axis=1)
        contributions["actual"] = y_actual.values
        return contributions

    def compute_roi(
        self, contributions: pd.DataFrame, channel_costs: dict
    ) -> dict:
        """
        ROI = Revenue Generated by Channel / Cost of Channel Activity
        Uses contribution as proxy for revenue impact.
        """
        roi = {}
        for channel, cost in channel_costs.items():
            if channel in contributions.columns and cost > 0:
                revenue_impact = contributions[channel].sum()
                roi[channel] = round(revenue_impact / cost, 4)
        return roi

    def evaluate(self, X: pd.DataFrame, y_true: pd.Series) -> dict:
        y_pred = self.predict(X)
        return {
            "r2": round(r2_score(y_true, y_pred), 4),
            "mae": round(mean_absolute_error(y_true, y_pred), 4),
            "rmse": round(np.sqrt(mean_squared_error(y_true, y_pred)), 4),
            "aic": round(self.model.aic, 2),
            "bic": round(self.model.bic, 2),
        }

    def simulate_scenario(
        self,
        X_base: pd.DataFrame,
        adjustments: dict,
    ) -> dict:
        """
        Simulate Rx impact of changing channel budgets.

        adjustments: dict of {channel: multiplier}
        e.g. {"log_rep_visits": 1.2} = increase rep visits by 20%
        """
        X_scenario = X_base.copy()
        for channel, multiplier in adjustments.items():
            if channel in X_scenario.columns:
                X_scenario[channel] = X_scenario[channel] * multiplier

        base_pred = np.expm1(self.predict(X_base)).sum()
        scenario_pred = np.expm1(self.predict(X_scenario)).sum()
        delta = scenario_pred - base_pred
        delta_pct = (delta / base_pred) * 100

        return {
            "base_rx_total": round(base_pred, 0),
            "scenario_rx_total": round(scenario_pred, 0),
            "delta_rx": round(delta, 0),
            "delta_pct": round(delta_pct, 2),
            "adjustments": adjustments,
        }

    def summary(self) -> str:
        return self.model.summary().as_text()
